# Generated by Django 4.1.12 on 2023-11-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(default='10', max_length=5, unique=True)),
                ('name', models.CharField(default='', max_length=30)),
                ('host_id', models.CharField(default='', max_length=64)),
                ('max_capacity', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('A', 'Active'), ('F', 'Finished')], default='A', max_length=1)),
            ],
        ),
    ]
