# Generated by Django 4.1.12 on 2023-10-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='preferences',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='name',
            new_name='group_name',
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
