# Generated by Django 4.1.12 on 2023-11-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.BigAutoField(default=4310021863, primary_key=True, serialize=False),
        ),
    ]
