# Generated by Django 4.1.12 on 2023-11-03 21:18

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_id_alter_group_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.CharField(default=builtins.id, max_length=10, primary_key=True, serialize=False),
        ),
    ]
