# Generated by Django 4.2.6 on 2023-11-28 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_recommendations_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=64)),
                ('categories', models.JSONField()),
                ('times', models.JSONField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('radius', models.FloatField()),
                ('group_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='groups.group')),
            ],
        ),
    ]
