name: Django Migrate

on:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: 0
      DB_HOST: ${{ env.DB_HOST }}
      DB_PORT: ${{ env.DB_PORT }}
      DB_NAME: ${{ env.DB_NAME }}
      DB_USER: ${{ env.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
    defaults:
      run:
        working-directory: ./api/optimeet/
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migrate Production DB
        run: |
          python manage.py makemigrations
          python manage.py migrate
