name: Django Migrate

on:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: 0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migrate Production DB
        run: |
          python manage.py makemigrations
          python manage.py migrate